use super::Token;

pub const SURROGATE_RANGE: std::ops::RangeInclusive<u32> = 0xd800..=0xdfff;

pub const SINGLE_CHAR_TOKENS: &[Token; 128] = &[
	/*   0 */ Token::Undetermined,
	/*   1 */ Token::Undetermined,
	/*   2 */ Token::Undetermined,
	/*   3 */ Token::Undetermined,
	/*   4 */ Token::Undetermined,
	/*   5 */ Token::Undetermined,
	/*   6 */ Token::Undetermined,
	/*   7 */ Token::Undetermined,
	/*   8 */ Token::Undetermined,
	/*   9 */ Token::Undetermined,
	/*  10 */ Token::Undetermined,
	/*  11 */ Token::Undetermined,
	/*  12 */ Token::Undetermined,
	/*  13 */ Token::Undetermined,
	/*  14 */ Token::Undetermined,
	/*  15 */ Token::Undetermined,
	/*  16 */ Token::Undetermined,
	/*  17 */ Token::Undetermined,
	/*  18 */ Token::Undetermined,
	/*  19 */ Token::Undetermined,
	/*  20 */ Token::Undetermined,
	/*  21 */ Token::Undetermined,
	/*  22 */ Token::Undetermined,
	/*  23 */ Token::Undetermined,
	/*  24 */ Token::Undetermined,
	/*  25 */ Token::Undetermined,
	/*  26 */ Token::Undetermined,
	/*  27 */ Token::Undetermined,
	/*  28 */ Token::Undetermined,
	/*  29 */ Token::Undetermined,
	/*  30 */ Token::Undetermined,
	/*  31 */ Token::Undetermined,
	/*  32 */ Token::Undetermined,
	/*  33 */ Token::Undetermined,
	/*  34 */ Token::Undetermined,
	/*  35 */ Token::Undetermined,
	/*  36 */ Token::Undetermined,
	/*  37 */ Token::Undetermined,
	/*  38 */ Token::Undetermined,
	/*  39 */ Token::Undetermined,
	/*  40 */ Token::LeftParen, // 0x28
	/*  41 */ Token::RightParen, // 0x29
	/*  42 */ Token::Undetermined,
	/*  43 */ Token::Undetermined,
	/*  44 */ Token::Comma, // 0x2C
	/*  45 */ Token::Undetermined,
	/*  46 */ Token::Undetermined,
	/*  47 */ Token::Undetermined,
	/*  48 */ Token::Undetermined,
	/*  49 */ Token::Undetermined,
	/*  50 */ Token::Undetermined,
	/*  51 */ Token::Undetermined,
	/*  52 */ Token::Undetermined,
	/*  53 */ Token::Undetermined,
	/*  54 */ Token::Undetermined,
	/*  55 */ Token::Undetermined,
	/*  56 */ Token::Undetermined,
	/*  57 */ Token::Undetermined,
	/*  58 */ Token::Colon, // 0x3A
	/*  59 */ Token::Semicolon, // 0x3B
	/*  60 */ Token::Undetermined,
	/*  61 */ Token::Undetermined,
	/*  62 */ Token::Undetermined, // 0x3E
	/*  63 */ Token::Undetermined,
	/*  64 */ Token::Undetermined,
	/*  65 */ Token::Undetermined,
	/*  66 */ Token::Undetermined,
	/*  67 */ Token::Undetermined,
	/*  68 */ Token::Undetermined,
	/*  69 */ Token::Undetermined,
	/*  70 */ Token::Undetermined,
	/*  71 */ Token::Undetermined,
	/*  72 */ Token::Undetermined,
	/*  73 */ Token::Undetermined,
	/*  74 */ Token::Undetermined,
	/*  75 */ Token::Undetermined,
	/*  76 */ Token::Undetermined,
	/*  77 */ Token::Undetermined,
	/*  78 */ Token::Undetermined,
	/*  79 */ Token::Undetermined,
	/*  80 */ Token::Undetermined,
	/*  81 */ Token::Undetermined,
	/*  82 */ Token::Undetermined,
	/*  83 */ Token::Undetermined,
	/*  84 */ Token::Undetermined,
	/*  85 */ Token::Undetermined,
	/*  86 */ Token::Undetermined,
	/*  87 */ Token::Undetermined,
	/*  88 */ Token::Undetermined,
	/*  89 */ Token::Undetermined,
	/*  90 */ Token::Undetermined,
	/*  91 */ Token::LeftSquare, // 0x5B
	/*  92 */ Token::Undetermined,
	/*  93 */ Token::RightSquare, // 0x5D
	/*  94 */ Token::Undetermined,
	/*  95 */ Token::Undetermined,
	/*  96 */ Token::Undetermined,
	/*  97 */ Token::Undetermined,
	/*  98 */ Token::Undetermined,
	/*  99 */ Token::Undetermined,
	/* 100 */ Token::Undetermined,
	/* 101 */ Token::Undetermined,
	/* 102 */ Token::Undetermined,
	/* 103 */ Token::Undetermined,
	/* 104 */ Token::Undetermined,
	/* 105 */ Token::Undetermined,
	/* 106 */ Token::Undetermined,
	/* 107 */ Token::Undetermined,
	/* 108 */ Token::Undetermined,
	/* 109 */ Token::Undetermined,
	/* 110 */ Token::Undetermined,
	/* 111 */ Token::Undetermined,
	/* 112 */ Token::Undetermined,
	/* 113 */ Token::Undetermined,
	/* 114 */ Token::Undetermined,
	/* 115 */ Token::Undetermined,
	/* 116 */ Token::Undetermined,
	/* 117 */ Token::Undetermined,
	/* 118 */ Token::Undetermined,
	/* 119 */ Token::Undetermined,
	/* 120 */ Token::Undetermined,
	/* 121 */ Token::Undetermined,
	/* 122 */ Token::Undetermined,
	/* 123 */ Token::LeftCurly, // 0x7B
	/* 124 */ Token::Undetermined,
	/* 125 */ Token::RightCurly, // 0x7D
	/* 126 */ Token::Undetermined, // 0x7E
	/* 127 */ Token::Undetermined,
];
